// Core TypeScript types for the Poker Bankroll & Session Tracker schema.
// These mirror the Supabase SQL schema in `supabase/schema.sql`.

export type SessionStatus = 'active' | 'completed';

export interface Player {
  id: string;
  name: string;
  nickname: string | null;
  created_at: string; // ISO timestamp
}

export interface Session {
  id: string;
  date: string; // ISO date (YYYY-MM-DD)
  location: string;
  status: SessionStatus;
   // duration_hours is optional and stored as a numeric in the DB, surfaced as string | null
  duration_hours?: string | null;
  created_at: string; // ISO timestamp
}

export interface Transaction {
  id: string;
  session_id: string;
  player_id: string;
  buy_in_amount: string; // numeric as string from Supabase
  cash_out_amount: string; // numeric as string from Supabase
  net_profit: string; // generated column (cash_out_amount - buy_in_amount)
  created_at: string; // ISO timestamp
}

// Optional: Database type compatible with @supabase/supabase-js
// This is useful if you want full type safety when using the Supabase client.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      players: {
        Row: Player;
        Insert: {
          id?: string;
          name: string;
          nickname?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          nickname?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      sessions: {
        Row: Session;
        Insert: {
          id?: string;
          date: string;
          location: string;
          status?: SessionStatus;
          duration_hours?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          date?: string;
          location?: string;
          status?: SessionStatus;
          duration_hours?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      transactions: {
        Row: Transaction;
        Insert: {
          id?: string;
          session_id: string;
          player_id: string;
          buy_in_amount?: string;
          cash_out_amount?: string;
          // net_profit is generated by the database
          created_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          player_id?: string;
          buy_in_amount?: string;
          cash_out_amount?: string;
          // net_profit is generated by the database
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'transactions_session_id_fkey';
            columns: ['session_id'];
            referencedRelation: 'sessions';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'transactions_player_id_fkey';
            columns: ['player_id'];
            referencedRelation: 'players';
            referencedColumns: ['id'];
          }
        ];
      };
    };
    Views: {
      // Define SQL views here later if needed (e.g., leaderboards).
    };
    Functions: {};
    Enums: {
      session_status: SessionStatus;
    };
    CompositeTypes: {};
  };
}
